### ISSUE TITLE
Can I reproduce demo?

### ISSUE THREAD

**Issue by MisterBrookT** [xf-zhao/Matcha-agent#1]
hi, thanks for your excellent work!

i want to know how to run the demo that you show in the Youtube,  i am not sure whether if i can reproduce the demo since "the configuration about robot is not open-sourced"  in README.    If yes, can you tell me how to reproduce?   Thanks!

**Comment by xf-zhao** [comment]
Hello @LouisTang2001, sorry for the late reply. 

At the time this repo was created, the NICOL robot is only restricted to our internal usage. But later the NICOL paper went public. And I think it is a good time to release the whole code!

However, it takes a little time to organise this. And now we have many LLMs available, I will modify the code for a cheaper (e.g. chatgpt) LLM instead of still using the original davinci-003 model (far more expensive!).

I am working on this and will let you know once available.

Thanks for your attention.

**Comment by Tomshine123** [comment]
Hi, I also got the same question that if the results can be reproduced by the current open-source code, I encountered quite a lot of bugs on dependencies, would appreciate if there is guidance on installation of the repo.

**Comment by xf-zhao** [comment]
Hi @Tomshine123 @LouisTang2001 ,
we recently refactored the codes and provided detailed documents for the installation. Please check the new release.

In short, everything, including the robot configurations in CoppeliaSim, is open-sourced and ready to run. You can follow the README.md to reproduce the demo.
